import React from 'react';
import { Container } from '@/components/foundation/Container';
import { Section } from '@/components/foundation/Section';
import { Heading } from '@/components/foundation/Heading';
import { Text } from '@/components/foundation/Text';
import { Button } from '@/components/atoms/Button';
import { Link } from '@/components/atoms/Link';
import {
  ShieldCheck,
  ArrowRight,
  Activity,
  Scale,
  FileText,
} from 'lucide-react';

const TERMS_SECTIONS = [
  {
    id: 'acceptance',
    num: '01',
    title: '1. Acceptance of Terms',
    content: [
      'By accessing or using the NorAI Technologies website, web dashboards, REST API endpoints, or micro-SaaS utilities (collectively, the "Services"), you agree to be bound by these Terms of Service.',
      'If you are entering into this agreement on behalf of a business entity, you represent that you have the authority to bind such entity to these Terms.',
    ],
  },
  {
    id: 'license',
    num: '02',
    title: '2. API License & Permitted Use',
    content: [
      'NorAi Technologies grants you a non-exclusive, non-transferable, revocable license to access and use our AI utilities in accordance with your subscription plan.',
      'You agree not to reverse engineer, decompile, or attempt to extract source model weights from NorAI neural inference pipelines.',
    ],
  },
  {
    id: 'privacy',
    num: '03',
    title: '3. Data Privacy & Zero Persistent Logging',
    content: [
      'We enforce a strict Zero Persistent Logging policy for standard API inferencing payloads. Input documents, resumes, or lecture recordings are processed in memory and immediately discarded upon response completion.',
      'Customer data is never sold, shared, or utilized to train public foundation models.',
    ],
  },
  {
    id: 'ip',
    num: '04',
    title: '4. Intellectual Property Rights',
    content: [
      'All output text summaries, candidate scores, flashcards, and digested briefs generated by our Services are the exclusive property of the user.',
      'NorAi retains all ownership rights to the underlying software architecture, micro-tools, brand assets, and proprietary orchestration algorithms.',
    ],
  },
  {
    id: 'liability',
    num: '05',
    title: '5. Limitation of Liability',
    content: [
      'NorAi Services are provided on an "AS IS" and "AS AVAILABLE" basis. To the maximum extent permitted by law, NorAI Technologies shall not be liable for any indirect, incidental, or consequential damages.',
      'Our maximum aggregate liability for any claims arising from the Services is limited to the amount paid by you in the 12 months preceding the claim.',
    ],
  },
  {
    id: 'law',
    num: '06',
    title: '6. Governing Law & Jurisdiction',
    content: [
      'These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles.',
      'Any legal action or proceeding arising under these Terms shall be brought exclusively in the courts located in Uttar Pradesh, India.',
    ],
  },
];

export default function TermsPage() {
  return (
    <div
      className="
        text-primary-800
        min-h-screen
        font-sans
        selection:bg-[var(--accent-500)]
        selection:text-[var(--bg-page)]

        bg-[linear-gradient(180deg,#F4F7FF_0%,#EEF2FF_25%,#F5F0FF_55%,#F4F7FF_100%)]
      "
    >
      {/* Hero Section */}
      <Section className="relative pt-12 pb-14 md:pt-20 md:pb-16 overflow-hidden isolate">
        {/* Cover Image — place your file at /public/images/hero-bg.jpg */}
        <div
          aria-hidden="true"
          className="absolute inset-0 bg-cover bg-center bg-no-repeat"
          style={{
            backgroundImage: "url('/images/hero-bg.jpg')",
            backgroundColor: 'var(--primary-900)',
          }}
        />

        {/* Tinted overlay so text stays readable over the image */}
        <div aria-hidden="true" className="absolute inset-0 bg-[var(--bg-page)]/20" />

        {/* AI Neural Network Animation */}
        <div
          aria-hidden="true"
          className="absolute inset-0 pointer-events-none overflow-hidden"
        >
          <div
            className="
              absolute
              -left-20
              top-1/2
              w-72
              h-72
              rounded-full
              bg-cyan-400/10
              blur-[100px]
              animate-pulse
            "
          />

          <div
            className="
              absolute
              -right-20
              top-1/3
              w-80
              h-80
              rounded-full
              bg-blue-500/10
              blur-[110px]
              animate-pulse
            "
            style={{ animationDelay: '1200ms' }}
          />

          {/* AI Node - Left */}
          <div className="absolute left-[15%] top-[30%]">
            <span
              className="
                block
                w-2
                h-2
                rounded-full
                bg-cyan-300
                shadow-[0_0_18px_rgba(103,232,249,0.9)]
                animate-pulse
              "
            />
            <span
              className="
                absolute
                -inset-3
                rounded-full
                border
                border-cyan-300/20
                animate-ping
              "
            />
          </div>

          {/* AI Node - Right */}
          <div className="absolute right-[22%] top-[25%]">
            <span
              className="
                block
                w-1.5
                h-1.5
                rounded-full
                bg-cyan-200
                shadow-[0_0_15px_rgba(103,232,249,0.8)]
                animate-pulse
              "
              style={{ animationDelay: '500ms' }}
            />
          </div>

          {/* AI Node - Bottom Left */}
          <div className="absolute left-[27%] bottom-[18%]">
            <span
              className="
                block
                w-1.5
                h-1.5
                rounded-full
                bg-blue-200
                shadow-[0_0_14px_rgba(147,197,253,0.8)]
                animate-pulse
              "
              style={{ animationDelay: '900ms' }}
            />
          </div>

          {/* AI Node - Bottom Right */}
          <div className="absolute right-[13%] bottom-[25%]">
            <span
              className="
                block
                w-2
                h-2
                rounded-full
                bg-cyan-300
                shadow-[0_0_18px_rgba(103,232,249,0.8)]
                animate-pulse
              "
              style={{ animationDelay: '1400ms' }}
            />
          </div>

          {/* Neural Connection Lines */}
          <div
            className="
              absolute
              left-[15.5%]
              top-[30.5%]
              w-32
              h-px
              origin-left
              rotate-[18deg]
              bg-gradient-to-r
              from-cyan-300/40
              to-transparent
              animate-pulse
            "
          />

          <div
            className="
              absolute
              right-[22%]
              top-[25%]
              w-28
              h-px
              origin-right
              -rotate-[20deg]
              bg-gradient-to-l
              from-cyan-300/30
              to-transparent
              animate-pulse
            "
            style={{ animationDelay: '700ms' }}
          />

          {/* Tiny Data Particles */}
          <span className="absolute left-[9%] top-[45%] w-1 h-1 rounded-full bg-cyan-200/70 animate-pulse" />
          <span
            className="absolute left-[35%] top-[20%] w-1 h-1 rounded-full bg-blue-200/70 animate-pulse"
            style={{ animationDelay: '300ms' }}
          />
          <span
            className="absolute right-[32%] top-[45%] w-1 h-1 rounded-full bg-cyan-200/70 animate-pulse"
            style={{ animationDelay: '800ms' }}
          />
          <span
            className="absolute right-[8%] top-[40%] w-1 h-1 rounded-full bg-cyan-300/70 animate-pulse"
            style={{ animationDelay: '1100ms' }}
          />
        </div>

        <Container size="default" className="relative z-10">
          <div className="text-center max-w-3xl mx-auto space-y-6">
            {/* Eyebrow Badge */}
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-white/30 bg-white/10 backdrop-blur-md text-white text-xs font-mono tracking-wide uppercase">
              <ShieldCheck className="w-3.5 h-3.5 text-[#DDF7FF]" aria-hidden="true" />
              <span>Legal &amp; Governance</span>
            </div>

            {/* Headline */}
            <Heading
              as="h1"
              variant="display-xl"
              className="font-display font-extrabold text-white tracking-[-0.03em] leading-[1.08] drop-shadow-[0_2px_12px_rgba(0,0,0,0.25)]"
            >
              Terms of{' '}
              <span className="text-[#DDF7FF] underline decoration-[color:var(--accent-mono)/0.6] underline-offset-8">
                Service
              </span>
            </Heading>

            {/* Subhead */}
            <Text
              variant="body-lg"
              className="font-mono text-sm text-[#E8F7FF] leading-relaxed drop-shadow-[0_1px_6px_rgba(0,20,50,0.35)]"
            >
              Effective Date: January 1, 2026 • NorAi Technologies Pvt. Ltd. • Uttar Pradesh, India
            </Text>
          </div>
        </Container>
      </Section>

      {/* Signature Element: Terms Telemetry Bar */}
      <Section
        className="
          py-4
          border-y
          border-blue-400/10
          bg-white/30
          backdrop-blur-md
        "
      >
        <Container size="default">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4 text-xs font-mono">
            <div className="flex items-center gap-2 text-primary-700">
              <Activity className="w-4 h-4 text-[var(--accent-500)]" aria-hidden="true" />
              <span className="font-bold text-primary-800 uppercase tracking-wider">NORAI_TERMS:</span>
              <span className="text-[var(--accent-mono)]">● GOVERNING LAW: UTTAR PRADESH, INDIA</span>
            </div>

            <div className="flex items-center gap-2 text-primary-700">
              <span
                className="
                  inline-flex
                  items-center
                  gap-1.5
                  text-xs
                  text-blue-600
                  bg-white/40
                  backdrop-blur-sm
                  px-3
                  py-1
                  rounded-lg
                  border
                  border-blue-400/15
                "
              >
                <Scale className="w-3.5 h-3.5 text-[var(--accent-500)]" aria-hidden="true" />
                ENTERPRISE SLA &amp; REST API PERMITTED USE
              </span>
            </div>
          </div>
        </Container>
      </Section>

      {/* Terms Body Section */}
      <Section
        className="
          relative
          py-16
          overflow-hidden
          bg-[radial-gradient(circle_at_8%_20%,rgba(59,130,246,0.06),transparent_32%),radial-gradient(circle_at_92%_70%,rgba(139,92,246,0.06),transparent_34%)]
        "
      >
        <Container size="default">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
            {/* Left Sidebar Table of Contents */}
            <div className="lg:col-span-4 sticky top-24 space-y-4 hidden lg:block">
              <div
                className="
                  relative
                  overflow-hidden
                  rounded-2xl
                  p-6
                  space-y-4

                  bg-white/50
                  backdrop-blur-xl

                  border
                  border-blue-400/15

                  shadow-[0_10px_40px_rgba(59,130,246,0.06)]
                "
              >
                <div className="text-xs font-mono font-bold text-[var(--accent-500)] uppercase tracking-wider flex items-center gap-2">
                  <FileText className="w-4 h-4" aria-hidden="true" />
                  Document Index
                </div>
                <nav className="space-y-1 text-xs font-mono">
                  {TERMS_SECTIONS.map((sec) => (
                    <a
                      key={sec.id}
                      href={`#${sec.id}`}
                      className="
                        flex items-center gap-3 py-1.5 px-2 rounded-lg
                        text-primary-700
                        hover:text-blue-600 hover:bg-white/60
                        transition-all group
                      "
                    >
                      <span className="text-blue-600 font-bold">{sec.num}</span>
                      <span className="truncate group-hover:text-blue-600">{sec.title.replace(/^\d+\.\s*/, '')}</span>
                    </a>
                  ))}
                </nav>
              </div>
            </div>

            {/* Right Main Content */}
            <div className="lg:col-span-8 space-y-10">
              {TERMS_SECTIONS.map((section) => (
                <div key={section.id} id={section.id} className="scroll-mt-28 space-y-4 border-b border-blue-400/10 pb-8">
                  <div className="flex items-center gap-3 font-mono text-xs">
                    <span className="px-2 py-0.5 rounded-lg bg-blue-500/10 border border-blue-400/20 text-[var(--accent-mono)] font-bold">
                      SECTION_{section.num}
                    </span>
                  </div>

                  <Heading as="h2" variant="heading-lg" className="font-display font-bold text-primary-800">
                    {section.title}
                  </Heading>

                  {section.content.map((p, idx) => (
                    <Text key={idx} variant="body-md" className="text-primary-700 leading-relaxed font-normal">
                      {p}
                    </Text>
                  ))}
                </div>
              ))}

              {/* Contact Legal Banner */}
              <div
                className="
                  relative
                  overflow-hidden
                  rounded-2xl
                  p-8
                  space-y-4

                  bg-white/50
                  backdrop-blur-xl

                  border
                  border-blue-400/30

                  shadow-[0_15px_50px_rgba(59,130,246,0.08)]
                "
              >
                <div
                  aria-hidden="true"
                  className="
                    absolute -top-20 -right-20 w-48 h-48 rounded-full
                    bg-blue-500/10 blur-[80px] pointer-events-none
                  "
                />
                <Heading as="h3" variant="heading-md" className="relative z-10 font-display font-bold text-primary-800">
                  Have Questions Regarding Our Terms?
                </Heading>
                <Text variant="body-sm" className="relative z-10 text-primary-700">
                  Contact our legal team directly at <strong className="text-blue-600 font-mono">noraitechnologies@gmail.com</strong> for custom enterprise agreement terms or DPA requests.
                </Text>
                <div className="relative z-10 pt-2">
                  <Link href="/contact">
                    <Button
                      variant="primary"
                      size="md"
                      className="
                        bg-gradient-to-r from-blue-600 to-indigo-600
                        hover:from-blue-700 hover:to-violet-600
                        text-white font-semibold px-6 py-2.5 rounded-lg
                        shadow-lg shadow-blue-500/20
                        hover:shadow-blue-500/30
                        transition-all duration-300
                      "
                    >
                      Contact Legal Team <ArrowRight className="w-4 h-4 ml-2 inline-block" aria-hidden="true" />
                    </Button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </Container>
      </Section>
    </div>
  );
}