import React from 'react';
import { Container } from '@/components/foundation/Container';
import { Section } from '@/components/foundation/Section';
import { Heading } from '@/components/foundation/Heading';
import { Text } from '@/components/foundation/Text';
import { Button } from '@/components/atoms/Button';
import { Link } from '@/components/atoms/Link';
import {
  ShieldCheck,
  ArrowRight,
  Activity,
  Scale,
  FileText,
} from 'lucide-react';

const TERMS_SECTIONS = [
  {
    id: 'acceptance',
    num: '01',
    title: '1. Acceptance of Terms',
    content: [
      'By accessing or using the NorAI Technologies website, web dashboards, REST API endpoints, or micro-SaaS utilities (collectively, the "Services"), you agree to be bound by these Terms of Service.',
      'If you are entering into this agreement on behalf of a business entity, you represent that you have the authority to bind such entity to these Terms.',
    ],
  },
  {
    id: 'license',
    num: '02',
    title: '2. API License & Permitted Use',
    content: [
      'NorAI Technologies grants you a non-exclusive, non-transferable, revocable license to access and use our AI utilities in accordance with your subscription plan.',
      'You agree not to reverse engineer, decompile, or attempt to extract source model weights from NorAI neural inference pipelines.',
    ],
  },
  {
    id: 'privacy',
    num: '03',
    title: '3. Data Privacy & Zero Persistent Logging',
    content: [
      'We enforce a strict Zero Persistent Logging policy for standard API inferencing payloads. Input documents, resumes, or lecture recordings are processed in memory and immediately discarded upon response completion.',
      'Customer data is never sold, shared, or utilized to train public foundation models.',
    ],
  },
  {
    id: 'ip',
    num: '04',
    title: '4. Intellectual Property Rights',
    content: [
      'All output text summaries, candidate scores, flashcards, and digested briefs generated by our Services are the exclusive property of the user.',
      'NorAI retains all ownership rights to the underlying software architecture, micro-tools, brand assets, and proprietary orchestration algorithms.',
    ],
  },
  {
    id: 'liability',
    num: '05',
    title: '5. Limitation of Liability',
    content: [
      'NorAI Services are provided on an "AS IS" and "AS AVAILABLE" basis. To the maximum extent permitted by law, NorAI Technologies shall not be liable for any indirect, incidental, or consequential damages.',
      'Our maximum aggregate liability for any claims arising from the Services is limited to the amount paid by you in the 12 months preceding the claim.',
    ],
  },
  {
    id: 'law',
    num: '06',
    title: '6. Governing Law & Jurisdiction',
    content: [
      'These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles.',
      'Any legal action or proceeding arising under these Terms shall be brought exclusively in the courts located in Uttar Pradesh, India.',
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="dark-ambient-bg text-slate-100 min-h-screen font-sans selection:bg-[#0CCAB1] selection:text-[#0B0F17]">
      {/* Hero Section */}
      <Section className="relative pt-12 pb-14 md:pt-20 md:pb-16 overflow-hidden">
        <Container size="default">
          <div className="text-center max-w-3xl mx-auto space-y-6">
            {/* Eyebrow Badge */}
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-white/10 bg-[#131924] text-slate-300 text-xs font-mono tracking-wide uppercase">
              <ShieldCheck className="w-3.5 h-3.5 text-[#0CCAB1]" aria-hidden="true" />
              <span>Legal &amp; Governance</span>
            </div>

            {/* Headline */}
            <Heading
              as="h1"
              variant="display-xl"
              className="font-display font-extrabold tracking-tight text-white leading-tight"
            >
              Terms of{' '}
              <span className="text-[#0CCAB1] underline decoration-[#0CCAB1]/40 underline-offset-8">
                Service
              </span>
            </Heading>

            {/* Subhead */}
            <Text variant="body-lg" className="text-slate-300 font-mono text-sm leading-relaxed">
              Effective Date: January 1, 2026 • NorAI Technologies Pvt. Ltd. • Uttar Pradesh, India
            </Text>
          </div>
        </Container>
      </Section>

      {/* Signature Element: Terms Telemetry Bar */}
      <Section className="py-4 border-y border-white/10 bg-[#131924]/60">
        <Container size="default">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4 text-xs font-mono">
            <div className="flex items-center gap-2 text-slate-400">
              <Activity className="w-4 h-4 text-[#0CCAB1]" aria-hidden="true" />
              <span className="font-bold text-white uppercase tracking-wider">NORAI_TERMS:</span>
              <span className="text-[#45F7D6]">● GOVERNING LAW: UTTAR PRADESH, INDIA</span>
            </div>

            <div className="flex items-center gap-2 text-slate-400">
              <span className="inline-flex items-center gap-1.5 text-xs text-[#45F7D6] bg-[#0B0F17] px-3 py-1 rounded border border-white/10">
                <Scale className="w-3.5 h-3.5 text-[#0CCAB1]" aria-hidden="true" />
                ENTERPRISE SLA &amp; REST API PERMITTED USE
              </span>
            </div>
          </div>
        </Container>
      </Section>

      {/* Terms Body Section */}
      <Section className="py-12">
        <Container size="default">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
            {/* Left Sidebar Table of Contents */}
            <div className="lg:col-span-4 sticky top-24 space-y-4 hidden lg:block">
              <div className="p-6 bg-[#131924] border border-white/10 rounded-xl space-y-4 shadow-xl">
                <div className="text-xs font-mono font-bold text-[#0CCAB1] uppercase tracking-wider flex items-center gap-2">
                  <FileText className="w-4 h-4" aria-hidden="true" />
                  Document Index
                </div>
                <nav className="space-y-2 text-xs font-mono">
                  {TERMS_SECTIONS.map((sec) => (
                    <a
                      key={sec.id}
                      href={`#${sec.id}`}
                      className="flex items-center gap-3 py-1.5 px-2 rounded text-slate-300 hover:text-white hover:bg-[#0B0F17] transition-all group"
                    >
                      <span className="text-[#0CCAB1] font-bold">{sec.num}</span>
                      <span className="truncate group-hover:text-[#0CCAB1]">{sec.title.replace(/^\d+\.\s*/, '')}</span>
                    </a>
                  ))}
                </nav>
              </div>
            </div>

            {/* Right Main Content */}
            <div className="lg:col-span-8 space-y-10">
              {TERMS_SECTIONS.map((section) => (
                <div key={section.id} id={section.id} className="scroll-mt-28 space-y-4 border-b border-white/10 pb-8">
                  <div className="flex items-center gap-3 font-mono text-xs text-[#0CCAB1]">
                    <span className="px-2 py-0.5 rounded bg-[#0B0F17] border border-white/10 font-bold">
                      SECTION_{section.num}
                    </span>
                  </div>

                  <Heading as="h2" variant="heading-lg" className="font-display font-bold text-white">
                    {section.title}
                  </Heading>

                  {section.content.map((p, idx) => (
                    <Text key={idx} variant="body-md" className="text-slate-300 leading-relaxed font-normal">
                      {p}
                    </Text>
                  ))}
                </div>
              ))}

              {/* Contact Legal Banner */}
              <div className="p-8 rounded-xl bg-[#131924] border border-[#0CCAB1]/40 space-y-4 shadow-xl">
                <Heading as="h3" variant="heading-md" className="font-display font-bold text-white">
                  Have Questions Regarding Our Terms?
                </Heading>
                <Text variant="body-sm" className="text-slate-300">
                  Contact our legal team directly at <strong className="text-[#0CCAB1] font-mono">noraitechnologies@gmail.com</strong> for custom enterprise agreement terms or DPA requests.
                </Text>
                <div className="pt-2">
                  <Link href="/contact">
                    <Button variant="primary" size="md" className="bg-[#0CCAB1] hover:bg-[#45F7D6] text-[#0B0F17] font-semibold px-6 py-2.5 rounded-lg shadow-lg shadow-[#0CCAB1]/20">
                      Contact Legal Team <ArrowRight className="w-4 h-4 ml-2 inline-block" aria-hidden="true" />
                    </Button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </Container>
      </Section>
    </div>
  );
}
