import React from 'react';
import { buildMetadata } from '@/lib/seo';
import { Container } from '@/components/foundation/Container';
import { Section } from '@/components/foundation/Section';
import { Heading } from '@/components/foundation/Heading';
import { Text } from '@/components/foundation/Text';
import { Button } from '@/components/atoms/Button';
import { Link } from '@/components/atoms/Link';
import { TiltCard } from '@/components/molecules/TiltCard';
import {
  ShieldCheck,
  FileText,
  Lock,
  Scale,
  CheckCircle2,
  ArrowRight,
} from 'lucide-react';

export const metadata = buildMetadata({
  path: '/terms',
  title: 'Terms of Service — NorAI Technologies',
  description: 'Review the Terms of Service governing the use of NorAI micro-tools, API endpoints, and enterprise automation services.',
});

const TERMS_SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: [
      'By accessing or using the NorAI Technologies website, web dashboards, REST API endpoints, or micro-SaaS utilities (collectively, the "Services"), you agree to be bound by these Terms of Service.',
      'If you are entering into this agreement on behalf of a business entity, you represent that you have the authority to bind such entity to these Terms.',
    ],
  },
  {
    id: 'license',
    title: '2. API License & Permitted Use',
    content: [
      'NorAI Technologies grants you a non-exclusive, non-transferable, revocable license to access and use our AI utilities in accordance with your subscription plan.',
      'You agree not to reverse engineer, decompile, or attempt to extract source model weights from NorAI neural inference pipelines.',
    ],
  },
  {
    id: 'privacy',
    title: '3. Data Privacy & Zero Persistent Logging',
    content: [
      'We enforce a strict Zero Persistent Logging policy for standard API inferencing payloads. Input documents, resumes, or lecture recordings are processed in memory and immediately discarded upon response completion.',
      'Customer data is never sold, shared, or utilized to train public foundation models.',
    ],
  },
  {
    id: 'ip',
    title: '4. Intellectual Property Rights',
    content: [
      'All output text summaries, candidate scores, flashcards, and digested briefs generated by our Services are the exclusive property of the user.',
      'NorAI retains all ownership rights to the underlying software architecture, micro-tools, brand assets, and proprietary orchestration algorithms.',
    ],
  },
  {
    id: 'liability',
    title: '5. Limitation of Liability',
    content: [
      'NorAI Services are provided on an "AS IS" and "AS AVAILABLE" basis. To the maximum extent permitted by law, NorAI Technologies shall not be liable for any indirect, incidental, or consequential damages.',
      'Our maximum aggregate liability for any claims arising from the Services is limited to the amount paid by you in the 12 months preceding the claim.',
    ],
  },
  {
    id: 'law',
    title: '6. Governing Law & Jurisdiction',
    content: [
      'These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles.',
      'Any legal action or proceeding arising under these Terms shall be brought exclusively in the courts located in Uttar Pradesh, India.',
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="dark-ambient-bg text-slate-100 min-h-screen font-sans selection:bg-blue-500 selection:text-white">
      {/* Hero Section */}
      <Section className="relative pt-12 pb-16 md:pt-20 md:pb-24 overflow-hidden">
        <Container size="default">
          <div className="text-center max-w-3xl mx-auto space-y-6">
            {/* Eyebrow Badge */}
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-blue-500/30 bg-blue-500/10 text-blue-400 text-xs font-semibold tracking-wide uppercase">
              <ShieldCheck className="w-3.5 h-3.5 text-blue-400" />
              <span>Legal & Governance</span>
            </div>

            {/* Headline */}
            <Heading
              as="h1"
              variant="display-xl"
              className="font-extrabold tracking-tight text-white leading-tight"
            >
              Terms of{' '}
              <span className="bg-gradient-to-r from-blue-400 via-sky-400 to-cyan-300 bg-clip-text text-transparent">
                Service
              </span>
            </Heading>

            {/* Subhead */}
            <Text variant="body-lg" className="text-slate-300 font-normal leading-relaxed">
              Effective Date: January 1, 2026 • NorAI Technologies Pvt. Ltd.
            </Text>
          </div>
        </Container>
      </Section>

      {/* Terms Body Section */}
      <Section className="py-12 border-t border-white/10">
        <Container size="default">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
            {/* Left Sidebar Table of Contents */}
            <div className="lg:col-span-4 sticky top-24 space-y-4 hidden lg:block">
              <TiltCard className="p-6 bg-slate-900/70 border border-white/10 space-y-4">
                <div className="text-xs font-mono font-bold text-blue-400 uppercase tracking-wider">
                  Document Index
                </div>
                <nav className="space-y-2 text-sm text-slate-300 font-medium">
                  {TERMS_SECTIONS.map((sec) => (
                    <a
                      key={sec.id}
                      href={`#${sec.id}`}
                      className="block py-1 hover:text-blue-400 transition-colors"
                    >
                      {sec.title}
                    </a>
                  ))}
                </nav>
              </TiltCard>
            </div>

            {/* Right Main Content */}
            <div className="lg:col-span-8 space-y-12">
              {TERMS_SECTIONS.map((section) => (
                <div key={section.id} id={section.id} className="scroll-mt-28 space-y-4 border-b border-white/10 pb-8">
                  <Heading as="h2" variant="heading-lg" className="font-extrabold text-white">
                    {section.title}
                  </Heading>

                  {section.content.map((p, idx) => (
                    <Text key={idx} variant="body-md" className="text-slate-300 leading-relaxed">
                      {p}
                    </Text>
                  ))}
                </div>
              ))}

              {/* Contact Legal Banner */}
              <div className="p-8 rounded-2xl bg-blue-500/10 border border-blue-500/30 space-y-4">
                <Heading as="h3" variant="heading-md" className="font-bold text-white">
                  Have Questions Regarding Our Terms?
                </Heading>
                <Text variant="body-sm" className="text-slate-300">
                  Contact our legal team directly at <strong className="text-white">contact@norai.asia</strong> for custom enterprise agreement terms or DPA requests.
                </Text>
                <div className="pt-2">
                  <Link href="/contact">
                    <Button variant="primary" size="md" className="bg-blue-600 hover:bg-blue-500 text-white font-semibold px-6 py-2.5 rounded-lg">
                      Contact Legal Team <ArrowRight className="w-4 h-4 ml-2 inline-block" />
                    </Button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </Container>
      </Section>
    </div>
  );
}
